//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiyLayer.Concrete.Entitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class firma
    {
        public int ID { get; set; }
        public string firmaAd { get; set; }
        public string adres { get; set; }
        public string telefon { get; set; }
        public string email { get; set; }
        public System.DateTime kurulus_tarihi { get; set; }
        public int calisan_sayisi { get; set; }
    }
}
