//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiyLayer.Concrete.Entitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class kullanıcıYetki
    {
        public int kullanıcıYetkiID { get; set; }
        public int kullanıcıID { get; set; }
        public int yetkiID { get; set; }
    
        public virtual kullanıcı kullanıcı { get; set; }
        public virtual yetki yetki { get; set; }
    }
}
