//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiyLayer.Concrete.Entitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int logID { get; set; }
        public System.DateTime zaman { get; set; }
        public int kullanıcıID { get; set; }
        public string seviye { get; set; }
        public string mesaj { get; set; }
    
        public virtual kullanıcı kullanıcı { get; set; }
    }
}
