//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiyLayer.Concrete.Entitiy
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class personel_takip_otomasyonuEntities : DbContext
    {
        public personel_takip_otomasyonuEntities()
            : base("name=personel_takip_otomasyonuEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<firma> firma { get; set; }
        public virtual DbSet<girisÇıkısBilgisi> girisÇıkısBilgisi { get; set; }
        public virtual DbSet<kullanıcı> kullanıcı { get; set; }
        public virtual DbSet<kullanıcıYetki> kullanıcıYetki { get; set; }
        public virtual DbSet<Log> Log { get; set; }
        public virtual DbSet<personel> personel { get; set; }
        public virtual DbSet<sube> sube { get; set; }
        public virtual DbSet<yetki> yetki { get; set; }
        public virtual DbSet<personel_sube> personel_sube { get; set; }
        public virtual DbSet<ApiResponse> ApiResponse { get; set; }
        public virtual DbSet<personelgiriscikis> personelgiriscikis { get; set; }
    }
}
