//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiyLayer.Concrete.Entitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class personelgiriscikis
    {
        public int ID { get; set; }
        public int personelID { get; set; }
        public int subeID { get; set; }
        public System.DateTime giris { get; set; }
        public System.DateTime cikis { get; set; }
    
        public virtual personel personel { get; set; }
    }
}
