//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiyLayer.Concrete.Entitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class personel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public personel()
        {
            this.girisÇıkısBilgisi = new HashSet<girisÇıkısBilgisi>();
            this.personel_sube = new HashSet<personel_sube>();
            this.personelgiriscikis = new HashSet<personelgiriscikis>();
        }
    
        public int personelID { get; set; }
        public string ad { get; set; }
        public string soyad { get; set; }
        public string tc { get; set; }
        public Nullable<System.DateTime> dogumTarihi { get; set; }
        public string cinsiyet { get; set; }
        public string adres { get; set; }
        public string telefon { get; set; }
        public string pozisyon { get; set; }
        public Nullable<decimal> maas { get; set; }
        public string kartseriNo { get; set; }
        public byte[] sicilDosyasi { get; set; }
        public string sicilDosyaAdi { get; set; }
        public byte[] ikametDosyasi { get; set; }
        public string ikametDosyaAdi { get; set; }
        public byte[] saglikRaporuDosyasi { get; set; }
        public string sagliKRaporuDosyasiAdi { get; set; }
        public byte[] mezunDosyasi { get; set; }
        public string mezunDosyasiAdi { get; set; }
        public byte[] kimlikDosyasi { get; set; }
        public string kimlikDosyasiAdi { get; set; }
        public string firmaGirisCikis { get; set; }
        public string fotograf { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<girisÇıkısBilgisi> girisÇıkısBilgisi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<personel_sube> personel_sube { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<personelgiriscikis> personelgiriscikis { get; set; }
    }
}
