//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiyLayer.Concrete.Entitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class sube
    {
        public int subeID { get; set; }
        public string subeAdi { get; set; }
        public string subeAdresi { get; set; }
        public string subeSehri { get; set; }
        public string subeTelefonu { get; set; }
        public string subeacilis_kapanis { get; set; }
        public string yetkiMUDUR { get; set; }
        public string yetkiYONETİCİ { get; set; }
    }
}
